spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cs21337?serverTimezone=GMT%2B8
    username: root
    password: mcxiaodandan153+
  data:
    redis:
      # 地址
      host: localhost
      # 数据库索引
      database: 2
      # 密码
      #      password: $2a$10$4NR/
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.sana: debug
server:
  port: 10908

sana:
  defaultAvatar: https://lovesana.oss-cn-beijing.aliyuncs.com/defaultAvatar.png